[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "f-tools"
version = "4.0.0"
description = "AWS tools including ECS bash execution"
readme = "README.md"
authors = [
    {name = "Filipe Ferreira", email = "code@filipeandre.com"}
]
dependencies = [
    "boto3",
    "inquirer",
]
urls = { "Homepage" = "https://github.com/filipeandre/f-tools" }

[tool.setuptools.package-data]
"f_tools.aws.resources" = ["*.sh"]

[project.scripts]
f-ecs-bash = "f_tools.aws.ecs_bash:main"