[project]
name = "simple-config-sync"
version = "0.1.21"
description = "This tool is used to synchronize dotfiles across various Linux devices, with capabilities to automatically create and delete links, as well as selectively synchronize files."
readme = "README.md"
authors = [{ name = "hmeqo", email = "hmeqocoliniliad@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    "textual>=0.52.1",
    "toml>=0.10.2",
    "click>=8.1.7",
    "mmh3>=4.1.0",
]

[project.scripts]
confsync = "simple_config_sync.core:run_cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/simple_config_sync"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["F401", "F403", "F405"]

[tool.ruff.format]
quote-style = "double"
