[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bitmapmaker"
version = "1.0.1"
authors = [
    { name="Ryan Kellar", email="rt.kellar@gmail.com" },
]
description = "A package for creating your own custom bitmaps from a windows GUI."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
Homepage = "https://github.com/Ruxton07/bitmapmaker"
Issues = "https://github.com/Ruxton07/bitmapmaker/issues"