[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0",
]

[project]
authors = [
    { email = "johannes-programming@mailfence.com", name = "Johannes" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "datarepr>=1.0.0",
    "frozendict>=2.4.6",
]
description = "This project provides holders for the arguments for callables."
keywords = []
name = "argshold"
readme = "README.rst"
requires-python = ">=3.8"
version = "0.0.2.dev0"

[project.license]
file = "LICENSE.txt"

[project.urls]
Documentation = "https://pypi.org/project/argshold"
Download = "https://pypi.org/project/argshold/#files"
Source = "https://github.com/johannes-programming/argshold"
