[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deezspot"
version = "2025.01.01"
description = "Downloads songs, albums, episode or playlists from deezer and spotify with this packages! (clone from https://pypi.org/project/deezloader/)"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GNU Affero General Public License v3"}
authors = [
    {name = "farihdzakyy", email = "farihmuhammad75@gmail.com"}
]

dependencies = [
    "mutagen",
    "pycryptodome",
    "requests",
    "spotipy",
    "tqdm",
    "fastapi",
    "uvicorn[standard]",
    "spotipy-anon",
    "librespot"
]

[project.urls]
Homepage = "https://github.com/farihdzkyy/deezspot"
Repository = "https://github.com/farihdzkyy/deezspot.git"
Documentation = "https://github.com/farihdzkyy/deezspot/blob/main/README.md"

[tool.setuptools]
packages = [
    "deezspot",
    "deezspot.models",
    "deezspot.spotloader", 
    "deezspot.deezloader",
    "deezspot.libutils"
]