[tool.poetry]
name = "leistungsbot"
version = "1.1.1"
description = ""
authors = ["EckPhi"]
readme = "README.md"
include = [{ path = "resources", format = ["sdist", "wheel"] }]

[tool.poetry.dependencies]
python = "^3.11"
pyTelegramBotAPI = "^4.5.0"
mysql-connector-python = "^9.0.0"
googlemaps = "^4.10.0"
pyyaml = "^6.0.2"
urllib3 = "^2.2.2"
schedule = "^1.2.2"
python-telegram-bot-calendar = "^1.0.5"
requests = "^2.32.3"
platformdirs = "^4.2.2"
confuse = "^2.0.1"


[tool.poetry.scripts]
leistungsbot = "leistungsbot.__main__:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
black = "24.4.2"
pre-commit = "^3.8.0"
genbadge = {extras = ["all"], version = "^1.1.1"}
coverage = "^7.6.1"
flake8 = "^7.1.1"


[tool.poetry-dynamic-versioning]
enable = false
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning.files."package/_version.py"]
persistent-substitution = true
initial-content = """
  # These version placeholders will be replaced later during substitution.
  __version__ = "0.0.0"
  __version_tuple__ = (0, 0, 0)
"""

[tool.mypy]
disallow_untyped_defs = true
