[project]
name = "Equimo"
version = "0.1.3a8"
description = "Implementation of popular vision models in Jax"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "einops>=0.8.0",
  "equinox>=0.11.5",
  "jax>=0.4.25",
  "jaxlib>=0.4.25",
]
