[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "audiometer"
version = "0.17.0"
requires-python = ">=3.10"
classifiers = [
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Software Development :: Libraries",
]

[project.optional-dependencies]
dev = [
    "pydub==0.25.1",
    "maturin==1.2.3",
    "pre-commit==3.4.0",
    "pytest==7.4.2",
]

[tool.maturin]
python-source = "python"
module-name = "audiometer._audiometer"

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "W"]