
"肉食类"=[
    "*肉*!*面*",
    "*鸡*!*蛋*!*精*",
    "*鸭*!*蛋*",
    "*牛*!*面*",
    "*羊*",
    "*猪*"
]
"粮食类"=[
    "*蛋黄派",
    "*米!*黄豆米*",
    "*町*",
    "*面*!*辣椒*",
    # "*玉米棒*",
    # "*玉米粒*",
    "*馒*",
    "*包",
    "*米线",
    "*卷粉",
    "*圆粉",
    "*扁粉"
]
"蛋奶及糕点类"=[
    "*蛋*!*蛋黄派*",
    "*奶*!*馒*",
]
"油类"=[
    "*油*!*蚝油*!*花椒油*!*酱油*!*油麦菜*!*老干妈*",
]
"调味类"=[
    "*葱*",
    "*姜*",
    "*蒜*!*蒜苔*",
    "*辣*",
    "*香菜*",
    "*糖*",
    "*八角*",
    "*草果*",
    "*花椒*",
    "*老干妈*",
    "*醋*",
    "*蘸*",
    "*酒*",
    "*盐*",
    "*蚝油*",
    "*酱油*",
    "*豆瓣酱*",
    "*味精*",
    "*鸡精*",
    "*生抽*",
    "*折耳根*",
    "*芹*",
    "*桂皮*",
    "*胡椒粉*",
    "*韭*",
]
"水果类"=[
    "*蕉*",
    "*苹果*",
    "*梨*",
]

# The end.
