[tool.poetry]
name = "uniteam-backend-package"
version = "0.1.2"
description = ""
authors = ["Fayaz Rafeek <fayaz@martiandays.com>"]
readme = "README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.10.4"
pandas = "^2.2.2"
psycopg2-binary = "^2.9.9"
python-json-logger = "^2.0.7"
flask = "^3.0.3"

[tool.poetry.dev-dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
