[tool.poetry]
name = "genesis-base"
version = "0.1.0"
description = "Genesis video processing base package"
authors = ["Genesis Team <steven.ge@godscode.com.cn>"]
readme = "README.md"
packages = [{include = "genesis_base", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^1.4.0"
pymysql = "^1.0.0"
pymongo = "^4.0.0"
boto3 = "^1.26.0"
pydantic = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
