[project]
name = "stingle-photos-toolkit"
version = "0.1.1"
authors = [
  { name="Alessandro Rinaldi", email="ale@alerinaldi.it" },
]
description = "A Python toolkit to interact with Stingle Photos database and data files"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
]
dependencies = [
    "bitarray>=3.0.0",
    "boto3>=1.35.94",
    "libnacl>=2.1.0",
    "mysql-connector-python>=9.1.0",
    "pynacl>=1.5.0",
]

[project.urls]
Homepage = "https://github.com/porech/stingle-photos-toolkit"
Issues = "https://github.com/porech/stingle-photos-toolkit/issues"
