[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "start-watching-sites"
version = "0.1.1"
authors = [{ name = "jaytrairat", email = "jay.trairat@gmail.com" }]
description = "Checking sites"
readme = "README.md"
requires-python = ">=3.12.1"

[tool.poetry]
packages = [{ include = "*", from = "src" }]

[tool.poetry.scripts]
start-watching-sites = "start_watching_sites.main:main"

[tool.poetry.dependencies]
python = ">=3.12.1"
tabulate = ">=0.9.0"
requests = ">=2.32.3"
tqdm = ">=4.67.1"
openpyxl = "^3.1.5"
sqlalchemy = "^2.0.36"
pytz = "^2024.2"
pandas = "^2.2.3"
