[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easedb"
version = "0.1.2"
authors = [
    {name = "Boylair <boylair@tuta.io>"}
]
description = "Fast, simple, reliable â€” Database management made easy"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Boylair/easedb"
"Bug Tracker" = "https://github.com/Boylair/easedb/issues"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]
markers = [
    "asyncio: mark a test as an asyncio coroutine",
]

[tool.coverage.run]
source = ["src/easedb"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
    "pass"
]

[project.scripts]
easedb = "easedb.cli.main:main"
