[project]
name = "dompa"
version = "0.8.0"
description = "A zero-depencency, extendable HTML5 parser."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Asko NÃµmm", email = "asko@nmm.ee" }
]
dependencies = []
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Development Status :: 4 - Beta"
]

[tool.black]
line-length = 100
