[build-system]
   requires = ["setuptools>=61.0", "wheel"]
   build-backend = "setuptools.build_meta"

   [project]
   name = "curl2req"
   version = "0.1.5"
   description = "bash curl transfer to requests"
   readme = "README.md"
   requires-python = ">=3.7"
   authors = [{ name = "weiz", email = "azhao.1981@gmail.com" }]
   license = { file = "LICENSE" }
   classifiers = [
       "Programming Language :: Python :: 3",
       "License :: OSI Approved :: MIT License",
       "Operating System :: OS Independent",
   ]
   dependencies = [
       "requests",
       "pydantic",
       "curlparser",
       "jsonpath_ng",
   ]

   [project.optional-dependencies]
   dev = [
       "pytest",
       "flake8",
       "sphinx",
   ]

   [project.urls]
   "Homepage" = "https://github.com/azhao1981/curl2req"
   "Bug Tracker" = "https://github.com/azhao1981/curl2req/issues"