[tool.poetry]
name = "gldcswpy"
version = "0.2.5"
description = "Generalized Lambda Distribution in CSW Parametrization for Python"
authors = ["Kavya Annapareddy <annapareddy.kavya@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/KavyaAnnapareddy/gldcswpy"
keywords = ["gld"]
classifiers = [
    "Topic :: Scientific/Engineering",
]

[tool.poetry.dependencies]
python = "^3.12"

pytest = ">= 7.4.0"
matplotlib = "^3.10.0"
scipy = "^1.15.0"
seaborn = "^0.13.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

