[project]
name = "ddx-ai"
version = "0.1.5"
description = "DDx is a system to solve complex math problems"
readme = "README.md"
requires-python = ">=3.12"
authors = [{name = "Diddigam Sai Praneeth", email = "johndoeknown@protonmail.com"}]
dependencies = [
    "openai>=1.58.1",
    "sympy>=1.13.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"