[tool.poetry]
name = "kathairo"
version = "0.3.1"
description = "A text processing pipeline for Scripture."
authors = ["Robertson Brinker <robertsonbrinker@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sil-thot = "^3.4.6"
usfm-grammar = "3.0.0b16"
pytest = "^8.0.2"
pandas = "^2.2.1"
pytest-xdist = "^3.5.0"
spacy = "^3.7.5"
sil-machine = "1.0.2"
polars = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
build-tsvs = "kathairo.tsvs.build_tsv_json_parser:main"