[project]
name = "easyfig"
version = "1.2.1"
authors = [
  { name = "Yu-Xin Tian", email = "neu.tianyuxin.2013@gmail.com" },
]
dependencies = [
	"numpy",
	"sympy",
	"matplotlib",
	"ipython",
	"notebook",
	"pyperclip",
	"antlr4-python3-runtime==4.10"
]
description = "A simple simulation plotting tool with GUI. 适合科研人员的Python快速仿真绘图工具版本！A Python tool for researchers to create figures for academic papers!"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/Jesse-tien/Easyfig"
"Bug Tracker" = "https://github.com/Jesse-tien/Easyfig/issues"
