[project]
name = "metacycle-core"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp-cors>=0.7.0",
    "aiohttp>=3.11.11",
    "python-socketio>=5.12.1",
]
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
metacycle-hello = "metacycle_core.hello:main"
