[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geofacetpy"
version = "0.1.1"
description = "Easily create geofaceted plots in matplotlib"
readme = "README.md"
authors = [{ name = "BartÅ‚omiej Remlein", email = "bartlomiej@remlein.pl" }]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = ["matplotlib>=3.5", "pandas"]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    'Topic :: Scientific/Engineering :: Visualization',
]
urls = { Homepage = "https://github.com/bartlomiejremlein/geofacetpy" }

[project.optional-dependencies]
test = ["pytest>=7.0", "pytest-cov>=3.0", "tox", "flake8"]

[tool.flake8]
max-line-length = 160
exclude = [".git", "__pycache__", "build", "dist", ".venv"]

[tool.setuptools]
packages = ["geofacetpy"]
