[project]
name = "mtmaisdk"
version = "0.5.44"
description = "A web scraping library based on LangChain which uses LLM and direct graph logic to create scraping pipelines."
authors = [
    { name = "Marco Vinciguerra", email = "mvincig11@gmail.com" },
]
dependencies = [
    "langchain>=0.3.0",
    "opentelemetry-api>=1.28.0",
    "opentelemetry-sdk>=1.28.0",
    "opentelemetry-instrumentation>=0.49b0",
    "opentelemetry-distro>=0.49b0",
    "opentelemetry-exporter-otlp>=1.28.0",
    "opentelemetry-exporter-otlp-proto-http>=1.28.0",
    "prometheus-client>=0.21.1",
    "grpcio>=1.68.1",
    "python-dotenv>=1.0.0",
    "protobuf>=5.29.1",
    "pyyaml>=6.0.1",
    "grpcio-tools>=1.68.1",
    "aiostream>=0.5.2",
    "nest-asyncio>=1.6.0",
    "aiohttp>=3.10.5",
    "aiohttp-retry>=2.8.3",
    "tenacity>=8.4.1",
    "cel-python>=0.1.5",
    "python-dateutil>=2.9.0.post0",
    "loguru>=0.7.3",
]

[build-system]
requires = ["hatchling>=1.0.0", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["mtmaisdk"]
exclude = [
    "tests/**",
    "examples/**",
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "mtmaisdk/_version.py"


# [tool.hatch.build.targets.wheel]
# packages = ["src"]

[tool.uv.sources]
mtmaisdk = { workspace = true }

[tool.hatch.build.targets.sdist]
include = [
    "src",
    "pyproject.toml",
    "README.md",
    "LICENSE",
]

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = [
    "burr[start]==0.22.1",
    "sphinx==6.0",
    "furo==2024.5.6",
]

[tool.uv]
dev-dependencies = [
    "poethepoet>=0.31.1",
    "pytest==8.0.0",
    "pytest-mock==3.14.0",
    "pylint>=3.2.5",
]
# 明确使用跟目录下的venv,否则在子项目安装依赖时会在子项目目录下创建venv
# venv-path = "../../.venv"
