[project]
name = "python-monads"
version = "0.0.7"
description = "Either and Maybe monads for Python"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Pol Dellaiera", email = "pol.dellaiera@protonmail.com" }]
license = { file = "LICENSE" }
keywords = ["monad", "functional-programmtion", "complexity"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/drupol/python-monads"
Repository = "https://github.com/drupol/python-monads.git"
Issues = "https://github.com/drupol/python-monads/issues"

[dependency-groups]
dev = ["pytest>=8.3.4"]

#########################################################################################
# Testing
#########################################################################################

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.coverage.report]
show_missing = true
fail_under = 98

[tool.coverage.html]
directory = "reports/coverage/html"

[tool.coverage.xml]
output = "reports/coverage/coverage.xml"

[tool.ruff.lint]
select = [
    # Error (https://docs.astral.sh/ruff/rules/#error-e_1)
    "E",
    # Pyflakes (https://docs.astral.sh/ruff/rules/#pyflakes-f)
    "F",
    # Pyupgrade (https://docs.astral.sh/ruff/rules/#pyupgrade-up)
    "UP",
    # isort (https://docs.astral.sh/ruff/rules/#isort-i)
    "I",
    # PEP8 Naming (https://docs.astral.sh/ruff/rules/#pep8-naming-n)
    "N",
    # Flake8 Comprehensions (https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4)
    "C4",
    # Flake8 Logging Format (https://docs.astral.sh/ruff/rules/#flake8-logging-log)
    "G",
    # Refactor (https://docs.astral.sh/ruff/rules/#refactor-r)
    "R",
    # Pydocstyle (https://docs.astral.sh/ruff/rules/#pydocstyle-d)
    # Not enabled yet, this is way too much work now
    # "D"
]
ignore = ["E501"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
