[tool.poetry]
name = "tikka"
version = "0.13.0"
description = "Tikka is a fast and light Python/Tk client to manage your Äž1 accounts"
authors = ["Vincent Texier <vit@free.fr>"]
include = [
    "tikka/locales/*/LC_MESSAGES/*.mo",
    "tikka/slots/pyqt/resources/gui/windows/*_rc.py",
    "tikka/slots/pyqt/resources/gui/widgets/*_rc.py",
    "tikka/slots/pyqt/resources/icons/*_rc.py",
]

[tool.poetry.scripts]
tikka = "tikka.__main__:main"

[tool.poetry.dependencies]
python = "^3.7.0"
duniterpy = {version = "1.1.1", allow-prereleases = true}
mnemonic = "^0.19"
yoyo-migrations = "^7.3.1"
#PyQt5 = ">=5.15.2,<5.15.11"
# poetry want to install pyqt5-qt5 5.15.11 (available for macOS only) but can not find it
# https://github.com/python-poetry/poetry/issues/8540
# split PyQt5 in two packages and constraint = 5.15.11 to fix this
# but after that pytestqt complains...
# 5.15.2 works on all platform including arm.
pyqt5 = ">=5.15.2,<5.15.11"
pyqt5-qt = ">=5.15.2,<5.15.11"
pyqt5-qt5 = ">=5.15.2,<5.15.11"
PyYAML = "^6.0"
substrate-interface = "^1.7.4"
python-sql = "^1.4.0"
qrcode = "^7.4.2"
opencv-contrib-python = "^4.8.0.74"
eth-typing = "^3.2"
eth-utils = "<2.3"

[tool.poetry.group.dev.dependencies]
black = "22.3.0"
mypy = "^0.790"
isort = "^4.0.0"
pytest = "^6.2.1"
pyinstaller = "^4.4"
pre-commit-hooks = {git = "https://github.com/Lucas-C/pre-commit-hooks", tag = "v1.5.4"}
gitlab-ci-linter = {git = "https://gitlab.com/devopshq/gitlab-ci-linter"}
PyQt5-stubs = "^5.15.2"
pytest-qt = "^4.0.2"
ruff = "^0.0.244"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
# profile = "black"
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
line_length = 88
split_on_trailing_comma = "True"

[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
# select = ["E", "F"]
ignore = ["PL", ]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["I"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))"

# Assume Python 3.7.
target-version = "py37"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
