[package]
name = "pysnaptest"
version = "0.1.6"
edition = "2021"
include = [
    "/pyproject.toml",
    "/README.md",
    "/LICENSE",
    "/rust-toolchain",
    "/src",
    "/python/pysnaptest",
    "/tests",
    "/.cargo",
    "!__pycache__",
    "!tests/.hypothesis",
    "!tests/.pytest_cache",
    "!*.so",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pysnaptest"
crate-type = ["cdylib"]

[dependencies]
insta = { version = "1.41", features = ["json", "csv"] }
pyo3 = { version = "0.23.1", features = ["generate-import-lib"] }
pythonize = "0.23.0"
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"

[features]
# must be enabled when building with `cargo build`, maturin enables this automatically
extension-module = ["pyo3/extension-module"]
