app_mode: speedy_iqa
backup_dir: /Users/ianselby/speedy_iqa/backups
backup_interval: 5
log_dir: /Users/ianselby/speedy_iqa/logs
max_backups: 10
normalise_images: false
radiobuttons_page1:
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Overall Quality
radiobuttons_page2:
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Contrast
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Noise
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Artefacts
task: General use
